name: Dependancy-Smoke-Regression-Execution

on:
  push:
    branches:
      - develop

jobs:
  Smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run SMOKE-CUCUMBER-CHROME

  Regression-test:
    runs-on: ubuntu-latest
    needs: [Smoke-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run REGRESSION-CUCUMBER-CHROME

  RunAll-Test:
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs: [Smoke-test,Regression-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run RUN-ALL-CUCUMBER-CHROME