name: Cypress-Cucumber-Chrome-GitHubPages-Multi-OS

on:
  push:
    branches:
      - develop

  schedule:
    - cron: '0 2 * * *'

jobs:
  Cypress-e2e-chrome-multi-OS:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run RUN-ALL-CUCUMBER-CHROME

      - name: Generate folder name with timestamp + commit info
        id: foldername
        run: |
            # Default UTC Time
            # TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
            # For Time Zone Specific Settings
            TIMESTAMP=$(TZ='America/Chicago' date +'%Y%m%d-%H%M%S')
            SHORT_SHA=$(git rev-parse --short HEAD)
            # Get first 20 chars of the commit message, replace spaces with underscores
            # MSG=$(git log -1 --pretty=%s | tr ' ' '_' | cut -c1-20)
            MSG=$(git log -1 --pretty=%s | tr ' ' '_')
            FOLDER_NAME="${TIMESTAMP}_${MSG}_${SHORT_SHA}"
            echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_OUTPUT

      - name: Prepare timestamped report directory
        run: |
          mkdir -p tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}
          mv cucumber-html-reports/* tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}/

      - name: Upload Cucumber HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-test-report
          path: reports/${{ steps.foldername.outputs.FOLDER_NAME }}

      - name: Deploy HTML report to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages

          cp -r tmp-gh-pages/* gh-pages/

          cd gh-pages
          git add .
          git commit -m "Add report ${{ steps.foldername.outputs.FOLDER_NAME }}"
          git push origin gh-pages

      - name: Show GitHub Pages URL
        run: |
          echo ""
          echo "============================================================="
          echo "✅ Cypress HTML Report is Live!"
          echo "🌐 URL:"
          echo "🔗 https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.foldername.outputs.FOLDER_NAME }}/"
          echo "============================================================="