name: Cypress-Cucumber-Chrome-S3-SLACK

on:
  push:
    branches:
      - Develop

jobs:
  Cypress-e2e-chrome-aws-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run RUN-ALL-CUCUMBER-CHROME

      - name: Generate folder name with timestamp + commit info
        id: foldername
        run: |
          TIMESTAMP=$(TZ='America/Chicago' date +'%Y%m%d-%H%M%S')
          SHORT_SHA=$(git rev-parse --short HEAD)
          MSG=$(git log -1 --pretty=%s | tr ' ' '_')
          FOLDER_NAME="${TIMESTAMP}_${MSG}_${SHORT_SHA}"
          echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_OUTPUT

      - name: Prepare timestamped report directory
        run: |
          mkdir -p tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}
          mv cucumber-html-reports/* tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}/

      - name: Upload Cucumber HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-test-report
          path: tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}

      - name: Upload HTML Report to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pip install awscli
          aws s3 cp "tmp-gh-pages/${{ steps.foldername.outputs.FOLDER_NAME }}/" "s3://my-cypress-reports-2025-chiranjeevi/cy-reports/${{ steps.foldername.outputs.FOLDER_NAME }}/" --recursive

      - name: Show S3 Report URL
        env: 
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo ""
          echo "============================================================"
          echo "✅ Cypress HTML Report uploaded to S3!"
          echo "🌐 URL:"
          echo "🔗 https://my-cypress-reports-2025-chiranjeevi.s3.${AWS_DEFAULT_REGION}.amazonaws.com/cy-reports/${{ steps.foldername.outputs.FOLDER_NAME }}/index.html"
          echo "============================================================"

      - name: Notify Slack with Report URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          REPORT_URL="https://my-cypress-reports-2025-chiranjeevi.s3.${AWS_DEFAULT_REGION}.amazonaws.com/cy-reports/${{ steps.foldername.outputs.FOLDER_NAME }}/index.html"
          COMMIT_MSG=$(git log -1 --pretty=%s)
          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH_NAME="${GITHUB_REF##*/}"
          TIMESTAMP=$(TZ='America/Chicago' date +'%Y-%m-%d %H:%M:%S %Z')
        
          curl -X POST -H 'Content-type: application/json' --data "{
          \"blocks\": [
                {
                  \"type\": \"header\",
                  \"text\": {
                    \"type\": \"plain_text\",
                    \"text\": \"🚀 Cypress Test Report Available!\",
                    \"emoji\": true
                  }
                },
                {
                  \"type\": \"section\",
                  \"fields\": [
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \":label: *Branch:*\n${BRANCH_NAME}\"
                    },
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \":bookmark: *Commit:*\n${COMMIT_MSG} \`(${SHORT_SHA})\`\"
                    },
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \":calendar: *Timestamp:*\n${TIMESTAMP}\"
                    }
                  ]
                },
                {
                  \"type\": \"actions\",
                  \"elements\": [
                    {
                      \"type\": \"button\",
                      \"text\": {
                        \"type\": \"plain_text\",
                        \"text\": \"🔍 View HTML Report\",
                        \"emoji\": true
                      },
                      \"url\": \"${REPORT_URL}\",
                      \"style\": \"primary\"
                    }
                  ]
                }
              ]
            }" $SLACK_WEBHOOK_URL
        